### ISSUE TITLE
Update to oauth2-client stable version

### ISSUE THREAD

**Issue by chekalsky** [j4k/oauth2-vkontakte#5]
Last version of league/oauth2-client is 1.4.1. This provider uses 0.5.

Could you update your provider to the new version please.

**Comment by j4k** [comment]
Sure, no problem I will take a look this weekend

**Comment by tinpansoul** [comment]
Any updates?

**Comment by j4k** [comment]
I'm crazy busy at work currently I've not had a chance to even look at this... Sorry guys :<

**Comment by tinpansoul** [comment]
Okay, i can make it.

But.. do we really need backward compatibility? There is too much changes between `0.5` and `1.0`.
For example, [User enity](https://github.com/thephpleague/oauth2-client/blob/0.5.0/src/Entity/User.php), that doesn't exists anymore.

I think, answer is no – because people will use this library only with `thephpleague/oauth2-client`. So, i'll make a fork for myself (and PR here) with these breaking changes (will be documented).

**Comment by tinpansoul** [comment]
PR is here ( #6 ) but i need help with writing success tests.

**Comment by j4k** [comment]
I will find some time this week to write some tests

**Comment by chekalsky** [comment]
@j4k Any updates? 😃

**Comment by TrogWarZ** [comment]
Tell us please, what type of work we need to merge this PR? Tests only? Or..?

**Comment by tinpansoul** [comment]
Is here any work i can do to help this PR getting merged?
